# =================================================================
# Prompt System Configuration
# File: prompts/config/prompt_config.yaml
# =================================================================

# File paths and locations
file_paths:
  test_generation_prompts: "prompts/templates/test_generation_v1_default.yaml"
  error_handling_prompts: "prompts/templates/error_handling.yaml"
  output_directory: "output/"
  backup_directory: "prompts/backups/"

# Default settings
defaults:
  template_selection: "automotive_default"
  error_template: "validation_failure"
  encoding: "utf-8"
  variable_format: "{variable_name}"

# Automatic template selection configuration
auto_selection:
  enabled: true
  fallback_to_default: true
  case_sensitive_matching: false

  # Confidence thresholds for automatic selection
  confidence_thresholds:
    high_confidence: 0.8 # Use specialized template
    medium_confidence: 0.5 # Use default with warning
    low_confidence: 0.2 # Ask user to specify

# Model-specific configurations
model_configurations:
  "llama3.1:8b":
    max_context_length: 4000
    recommended_templates:
      - "automotive_default"
      - "door_control_specialized"
    timeout_seconds: 300
    temperature: 0.0

  "deepseek-coder-v2:16b":
    max_context_length: 8000
    recommended_templates:
      - "door_control_specialized"
      - "window_control_specialized"
    timeout_seconds: 600
    temperature: 0.0

# Validation and quality control
validation:
  # Template validation
  validate_yaml_syntax: true
  check_required_variables: true
  validate_template_references: true

  # Runtime validation
  check_variable_substitution: true
  validate_output_format: true
  monitor_template_performance: true

# Logging and monitoring
logging:
  log_template_selection: true
  log_variable_substitution: false
  log_rendering_time: true
  log_success_rates: true

  # Log file locations
  template_usage_log: "logs/template_usage.log"
  error_log: "logs/prompt_errors.log"
  performance_log: "logs/prompt_performance.log"

# Cache configuration
caching:
  enabled: true
  cache_rendered_prompts: false # Templates change frequently
  cache_template_metadata: true
  cache_selection_rules: true
  cache_duration_minutes: 60

# Development and testing
development:
  hot_reload: true # Reload templates when files change
  validation_mode: "strict" # strict|relaxed|disabled
  debug_variable_substitution: false
  test_mode: false
